const List<Map<String, String>> languages = [
  {'code': 'en', 'name': 'English'},
  {'code': 'es', 'name': 'Español'},
  {'code': 'fr', 'name': 'Français'},
  {'code': 'de', 'name': 'Deutsch'},
  {'code': 'it', 'name': 'Italiano'},
  {'code': 'pt', 'name': 'Português'},
  {'code': 'ru', 'name': 'Русский'},
  {'code': 'zh', 'name': '中文'},
  {'code': 'ja', 'name': '日本語'},
  {'code': 'ko', 'name': '한국어'},
  {'code': 'ar', 'name': 'العربية'},
  {'code': 'hi', 'name': 'हिन्दी'},
  {'code': 'bn', 'name': 'বাংলা'},
  {'code': 'ur', 'name': 'اردو'},
  {'code': 'tr', 'name': 'Türkçe'},
  {'code': 'nl', 'name': 'Nederlands'},
  {'code': 'pl', 'name': 'Polski'},
  {'code': 'sv', 'name': 'Svenska'},
  {'code': 'fi', 'name': 'Suomi'},
  {'code': 'da', 'name': 'Dansk'},
  {'code': 'no', 'name': 'Norsk'},
  {'code': 'el', 'name': 'Ελληνικά'},
  {'code': 'he', 'name': 'עברית'},
  {'code': 'th', 'name': 'ไทย'},
  {'code': 'vi', 'name': 'Tiếng Việt'},
  {'code': 'id', 'name': 'Bahasa Indonesia'},
  {'code': 'ms', 'name': 'Bahasa Melayu'},
  {'code': 'fa', 'name': 'فارسی'},
  {'code': 'uk', 'name': 'Українська'},
  {'code': 'cs', 'name': 'Čeština'},
];
